name: Update Version in index.html

on:
  push:
	paths:
	  - 'index.html'

jobs:
  update-version:
	runs-on: ubuntu-latest
	steps:
	  - name: Checkout code
		uses: actions/checkout@v2
		with:
		  fetch-depth: 0
	  
	  - name: Get current timestamp and commit ID
		id: version
		run: |
		  TIMESTAMP=$(date +'%M%S')
		  COMMIT_ID=$(git rev-parse --short HEAD)
		  echo "VERSION=${TIMESTAMP}${COMMIT_ID}" >> $GITHUB_ENV

	  - name: Replace VERSION_PLACEHOLDER
		run: |
		  sed -i "s/<!-- VERSION_PLACEHOLDER -->/${{ env.VERSION }}/g" index.html

	  - name: Commit and push changes
		run: |
		  git config --global user.name 'github-actions'
		  git config --global user.email 'github-actions@github.com'
		  git add index.html
		  git commit -m "Update version to ${{ env.VERSION }}"
		  git push
